---
- hosts: rnb
  become: True
  tasks:

    - name: Removing old folder
      command: "rm -rf Git-Jenkins-Maven-Docker-Ansible-Kubernetes-tomcat"
      
    - name: Git clone
      command: "git clone https://github.com/Raam043/Git-Jenkins-Maven-Docker-Ansible-Kubernetes-tomcat.git"
      
    - name: Enter the folder
      command: "cd Git-Jenkins-Maven-Docker-Ansible-Kubernetes-tomcat"
      
    - name: Deploying manifest files
      command: "kubectl get all"
      
    - name: Restarting the service
      command: "kubectl rollout restart deployment"
