---
- hosts: rnb
  become: True
  tasks:

    - name: Removing old folder
      command: "rm -rf Git-Jenkins-Maven-Docker-Ansible-Argo-Kubernetes"
      
    - name: Git clone
      command: "git clone https://github.com/Raam043/CICD-Git-jenkins-maven-tomcat.git"
      
    - name: Deploying manifest files
      command: "kubectl apply -f CICD-Git-jenkins-maven-tomcat/deployment.yml"
      
    - name: Restarting the service
      command: "kubectl rollout restart deployment"
