apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-project
  labels:
    app: tomcat-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-project
  strategy:
    type: RollingUpdate   
    rollingUpdate:
      maxSurge: 2       
                          
      maxUnavailable: 0   
  template:
    metadata:
      labels:
        app: tomcat-project
    spec:
      containers:
      - image: raam043/tomcat-project
        imagePullPolicy: Always
        name: tomcat-project
        ports:
        - containerPort: 8080
        

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-project
 
spec:
  ports:
  - port: 8080
    targetPort: 8080
  
  selector:
    app: tomcat-project
  type: LoadBalancer
